### ISSUE TITLE
can't work on linux kernel 2.6.32.67

### ISSUE THREAD

**Issue by mail2li** [tonyho/Generate_Kernel_Uboot_Project_forIDE#2]
downloaded kernel 2.6.32.67 from https://www.kernel.org/
and get error as :
--------------------------------------------------------------------------------Source code type is: [kernel]

--------------------------------------------------------------------------------Header file list in relative path mode
Header file[.h] Index:      [1547]
--------------------------------------------------------------------------------Header file list in absolutely path mode
Header file[.h] Index:      [1663]sed: can't read valid_filelist.txt: No such file or directory

cat: valid_filelist.txt: No such file or directory
sed: can't read Gen_Tmp/Valid_SRC.txt: No such file or directory
sed: can't read valid_filelist.txt: No such file or directory
cat: valid_filelist.txt: No such file or directory
sed: can't read valid_filelist.txt: No such file or directory
sed: can't read valid_filelist.txt: No such file or directory
cat: valid_filelist.txt: No such file or directory
sed: can't read valid_filelist.txt: No such file or directory
cp: cannot stat ‘valid_filelist.txt’: No such file or directory
cat: Gen_Tmp/Valid_SRC.txt: No such file or directory
mv: cannot stat ‘FileList_understand.txt’: No such file or directory
# 

but in kernel 4.1 it's work fine.

**Comment by tonyho** [comment]
Old kernel problem fixed. If problem still there, please let me know, thanks.
